var num1 = Math.floor(Math.random() * 50) + 1;
var num2 = Math.floor(Math.random() * 50) + 1;
var num3 = Math.floor(Math.random() * 50) + 1;
var num4 = Math.floor(Math.random() * 50) + 1;
var num5 = Math.floor(Math.random() * 50) + 1;
var max = Math.max(num1, num2, num3, num4, num5);
var min = Math.min(num1, num2, num3, num4, num5);
var average = (num1 + num2 + num3 + num4 + num5) / 5;
console.log("Numbers:", num1, num2, num3, num4, num5);
console.log("Largest:", max);
console.log("Smallest:", min);
console.log("Average:", average.toFixed(2));